Getbeans/Beans

lib/api/admin-menu.php
lib/api/compiler/class-options.php
lib/api/image/class-options.php

Resubmit pull request with valid contribute rule.

Added translation strings.

---

lib/templates/fragments/comments.php
lib/templates/fragments/post-shortcodes.php
lib/templates/structure/comment.php
lib/templates/structure/content.php
lib/templates/structure/loop.php

Fixed structured data testing tool error. [See here](https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252Fdemo.getbeans.io%252F).
Re-submit pull request for valid contribute rule.
@ThierryA Thank you for the great themes also sorry to take your time. I'm new to git.

Fixed structured data errors.

---

tests/phpunit/bootstrap.php
tests/phpunit/unit-tests/api/utilities/beansGet.php
tests/phpunit/unit-tests/api/utilities/beansMultiArrayKeyExists.php
tests/phpunit/unit-tests/api/utilities/beansPathToUrl.php
tests/phpunit/unit-tests/api/utilities/beansRemoveDir.php
tests/phpunit/unit-tests/api/utilities/beansRenderFunction.php
tests/phpunit/unit-tests/api/utilities/beansRenderFunctionArray.php
tests/phpunit/unit-tests/api/utilities/beansSanitizePath.php
tests/phpunit/unit-tests/api/utilities/beansUrlToPath.php

Existed in setup of each utility unit test.

Fixed extra forwardslash in loading api utility file

---

tests/phpunit/unit/api/utilities/beansGet.php
tests/phpunit/unit/api/utilities/beansMultiArrayKeyExists.php
tests/phpunit/unit/api/utilities/beansPathToUrl.php
tests/phpunit/unit/api/utilities/beansRemoveDir.php
tests/phpunit/unit/api/utilities/beansRenderFunction.php
tests/phpunit/unit/api/utilities/beansRenderFunctionArray.php
tests/phpunit/unit/api/utilities/beansSanitizePath.php
tests/phpunit/unit/api/utilities/beansUrlToPath.php

Includes more fixes than mentioned in the issue.
composer phpcs-tests and composer test-unit pass locally.

Fixed #74 - Inconsistencies and typos in tests.

---

lib/templates/fragments/comments.php
lib/templates/fragments/post.php

Issue 91: fix next icons closing markup ids

---

composer.json
tests/phpunit/integration/bootstrap.php
tests/phpunit/unit/api/utilities/beansPathToUrl.php
tests/phpunit/unit/api/utilities/beansSanitizePath.php
tests/phpunit/unit/bootstrap.php

- Improved the tests bootstrap files for consistency and readability.
- Fixed the PSR mapping for the tests in Composer.
- Forced colors in the Composer shortcut scripts.

Tests Bootstrap improvements

---

lib/api/template/functions.php
phpunit.xml.dist
tests/phpunit/integration/api/template/beansLoadDefaultTemplate.php
tests/phpunit/integration/api/template/beansLoadFragmentFile.php
tests/phpunit/unit/api/template/beansLoadDefaultTemplate.php
tests/phpunit/unit/api/template/beansLoadFragmentFile.php
tests/phpunit/unit/api/template/includes/class-template-test-case.php

2. Added unit and integration tests.
3. Improved the documentation.
4. Returned true/false after loading.

Made the Template API WPCS compliant & tested.

---

404.php
comments.php
footer.php
functions.php
header.php
index.php
page.php
search.php
sidebar-primary.php
sidebar-secondary.php
sidebar.php
single.php

WPCS compliance - Root files

---

lib/admin/options.php
lib/admin/updater.php
lib/admin/wp-customize.php

`@ignore` on line 15 and line 79 of updater.php

WPCS Compliance - Files in lib\admin

---

lib/api/compiler/class-options.php
lib/api/compiler/class-page-compiler.php

Covers the two files not included in PR 108.
I was not sure if I could change $depedencies but I can revert it right away.

Made lib\api\compiler WPCS compliant

---

lib/api/image/class-options.php
lib/api/image/functions.php

Does not take changes in PR 116 into account.

Made lib\api\image WPCS compliant

---

lib/api/post-meta/functions.php
tests/phpunit/integration/api/post-meta/beansGetPostMeta.php
tests/phpunit/unit/api/post-meta/beansGetPostMeta.php

1. Added unit and integration tests.
2. Improved documentation.
3. Changed `$field_id` to `$meta_key`.

Added tests for beans_get_post_meta().

---

lib/api/fields/class.php
lib/api/term-meta/functions.php
tests/phpunit/integration/api/term-meta/beansGetTermMeta.php
tests/phpunit/unit/api/term-meta/beansGetTermMeta.php

* Adds unit and integration tests for `beans_get_term_meta()`.
* Fixes #146

Add tests for beans_get_term_meta()

---

lib/api/html/functions.php

Made lib\api\html\functions WPCS compliant

---

tests/phpunit/unit/api/layout/beansGetDefaultLayout.php
tests/phpunit/unit/api/layout/beansGetLayout.php
tests/phpunit/unit/api/layout/beansGetLayoutClass.php

1. Mocked `beans_get()` in unit test.
2. Standardized the `setUp()` DocBlock.

Improved Layout API unit tests

---

tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php
tests/phpunit/unit/api/image/beans-image-editor/run.php
tests/phpunit/unit/api/image/includes/class-image-test-case.php

Improved Image API unit tests

---

tests/phpunit/unit/api/fields/includes/class-fields-test-case.php
tests/phpunit/unit/api/html/includes/class-html-test-case.php
tests/phpunit/unit/api/image/includes/class-image-test-case.php
tests/phpunit/unit/api/layout/beansGetDefaultLayout.php
tests/phpunit/unit/api/layout/beansGetLayout.php
tests/phpunit/unit/api/layout/beansGetLayoutClass.php
tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
tests/phpunit/unit/api/template/includes/class-template-test-case.php
tests/phpunit/unit/api/term-meta/beansGetTermMeta.php
tests/phpunit/unit/class-test-case.php

Standardized unit test file loading, i.e. to wait until after Patchwork is setup and using the load function.

Standardized unit test file loading.

---

lib/api/html/functions.php
tests/phpunit/integration/api/html/beansWrapMarkup.php
tests/phpunit/unit/api/html/beansWrapMarkup.php
tests/phpunit/unit/api/html/fixtures/class-anonymous-action-stub.php

1. Added unit tests.
2. Added integration tests.
3. Improved the function's DocBlock.

Added tests & improved documentation for beans_wrap_markup.

---

composer.json

Added composer script to run both PHPUnit test suites

---

composer.json

Changed composer script for grouped sniffers for consistency with grouped tests

---

lib/api/filters/functions.php
lib/api/html/functions.php
tests/phpunit/integration/api/html/beansRemoveOutput.php
tests/phpunit/unit/api/html/beansRemoveOutput.php
tests/phpunit/unit/api/html/fixtures/class-anonymous-filter-stub.php

1. Added integration and unit tests.
2. Improved function's documentation.
3. Added a crazy high priority number to ensure it fires last.

Tested beans_remove_output

---

lib/api/html/functions.php
tests/phpunit/integration/api/html/beansModifyMarkup.php
tests/phpunit/unit/api/html/beansModifyMarkup.php

1. Added unit and integration tests.
2. Improvement documentation.

Tested beans_markup_markup

---

lib/api/compiler/class-beans-compiler.php
tests/phpunit/unit/api/compiler/beans-compiler/addContentMediaQuery.php
tests/phpunit/unit/api/compiler/beans-compiler/cacheFile.php
tests/phpunit/unit/api/compiler/beans-compiler/cacheFileExist.php
tests/phpunit/unit/api/compiler/beans-compiler/combineFragments.php
tests/phpunit/unit/api/compiler/beans-compiler/fileystem.php
tests/phpunit/unit/api/compiler/beans-compiler/formatContent.php
tests/phpunit/unit/api/compiler/beans-compiler/get.php
tests/phpunit/unit/api/compiler/beans-compiler/getExtension.php
tests/phpunit/unit/api/compiler/beans-compiler/getFunctionContent.php
tests/phpunit/unit/api/compiler/beans-compiler/getInternalContent.php
tests/phpunit/unit/api/compiler/beans-compiler/getRemoteContent.php
tests/phpunit/unit/api/compiler/beans-compiler/replaceCssUrl.php
tests/phpunit/unit/api/compiler/beans-compiler/runCompiler.php
tests/phpunit/unit/api/compiler/beans-compiler/setFilename.php
tests/phpunit/unit/api/compiler/beans-compiler/setFragments.php
tests/phpunit/unit/api/compiler/includes/class-compiler-test-case.php
tests/phpunit/unit/class-test-case.php

1. Mocked all dependencies for pure unit tests.
2. Refactored for readability and DRY.

Improved Compiler API Unit Tests.

---

lib/api/post-meta/functions-admin.php
lib/api/post-meta/functions.php
tests/phpunit/integration/api/post-meta/beans-post-meta/construct.php
tests/phpunit/integration/api/post-meta/beans-post-meta/okToSave.php
tests/phpunit/integration/api/post-meta/beans-post-meta/renderMetaboxContent.php
tests/phpunit/integration/api/post-meta/beans-post-meta/renderNonce.php
tests/phpunit/integration/api/post-meta/beans-post-meta/save.php
tests/phpunit/integration/api/post-meta/beansIsPostMetaConditions.php
tests/phpunit/integration/api/post-meta/beansPostMetaPageTemplateReload.php
tests/phpunit/integration/api/post-meta/beansRegisterPostMeta.php
tests/phpunit/integration/api/post-meta/includes/class-beans-post-meta-test-case.php
tests/phpunit/unit/api/post-meta/beans-post-meta/okToSave.php
tests/phpunit/unit/api/post-meta/beans-post-meta/renderMetaboxContent.php
tests/phpunit/unit/api/post-meta/beans-post-meta/renderNonce.php
tests/phpunit/unit/api/post-meta/beans-post-meta/save.php
tests/phpunit/unit/api/post-meta/beansIsPostMetaConditions.php
tests/phpunit/unit/api/post-meta/beansPostMetaPageTemplateReload.php
tests/phpunit/unit/api/post-meta/beansRegisterPostMeta.php

Sorry, I didn't have time to comment earlier.

Improved consistency of Post Meta tests

---

tests/phpunit/integration/api/compiler/beans-compiler-options/flush.php
tests/phpunit/integration/api/compiler/beans-compiler-options/register.php
tests/phpunit/integration/api/compiler/beans-compiler-options/renderFlushButton.php
tests/phpunit/integration/api/compiler/beans-compiler-options/renderScriptsNotCompiledNotice.php
tests/phpunit/integration/api/compiler/beans-compiler-options/renderStylesNotCompiledNotice.php
tests/phpunit/integration/api/compiler/beans-compiler-options/renderSuccessNotice.php
tests/phpunit/integration/api/compiler/includes/class-compiler-options-test-case.php
tests/phpunit/unit/api/compiler/beans-compiler-options/flush.php
tests/phpunit/unit/api/compiler/beans-compiler-options/register.php
tests/phpunit/unit/api/compiler/beans-compiler-options/renderScriptsNotCompiledNotice.php
tests/phpunit/unit/api/compiler/beans-compiler-options/renderStylesNotCompiledNotice.php
tests/phpunit/unit/api/compiler/beans-compiler-options/renderSuccessNotice.php
tests/phpunit/unit/api/compiler/includes/class-compiler-options-test-case.php

This PR captures the code review from @christophherr, which came in after PR #220 was merged.

Improved tests per PR 220 review.

---

lib/templates/fragments/comments.php
lib/templates/fragments/footer.php
lib/templates/fragments/menu.php
lib/templates/fragments/post.php

- Wraps post, posts and comment pagination in `<nav>` elements and adds `aria-labels`
- Changes rel="designer" to rel="nofollow" 
closes #217

Fixed HTML validator errors

---

lib/api/components.php
lib/api/html/accessibility.php
lib/api/html/assets/js/skip-link-fix.js
lib/api/layout/functions.php
lib/assets/less/style.less
lib/templates/fragments/menu.php
lib/templates/structure/content.php
lib/templates/structure/header.php
lib/templates/structure/sidebar-primary.php
lib/templates/structure/sidebar-secondary.php
tests/phpunit/integration/api/html/beansBuildSkipLinks.php
tests/phpunit/integration/api/html/includes/class-html-test-case.php
tests/phpunit/integration/api/layout/beansHasPrimarySidebar.php
tests/phpunit/integration/api/layout/beansHasSecondarySidebar.php
tests/phpunit/integration/api/template/beansLoadDefaultTemplate.php
tests/phpunit/unit/api/html/beansBuildSkipLinks.php
tests/phpunit/unit/api/html/includes/class-html-test-case.php
tests/phpunit/unit/api/layout/beansHasPrimarySidebar.php
tests/phpunit/unit/api/layout/beansHasSecondarySidebar.php

Added skip links.

---

lib/init.php
style.css

In getting ready for our beta release, this PR upticks the current version from 1.4.1 to 1.5.0-beta.

Changed Beans version from 1.4.1 to 1.5.0-beta.

---

lib/languages/tm-beans.pot
style.css

This PR updates the .pot file for v.1.5.0-beta.
It also updates the getbeans.io URI in the stylesheet.

Updated languages POT file.

---

tests/phpunit/integration/api/filters/beansAddAnonymousFilter.php
tests/phpunit/integration/api/filters/beansAddFilter.php
tests/phpunit/integration/api/filters/beansApplyFilters.php
tests/phpunit/integration/api/filters/fixtures/test-filters.php
tests/phpunit/integration/api/filters/includes/class-filters-test-case.php
tests/phpunit/unit/api/filters/beans-anonymous-filters/_construct.php
tests/phpunit/unit/api/filters/beansAddFilter.php
tests/phpunit/unit/api/filters/beansApplyFilters.php
tests/phpunit/unit/api/filters/fixtures/test-filters.php
tests/phpunit/unit/api/filters/includes/class-filters-test-case.php

Updated array syntax of test for filters API.

---

tests/phpunit/integration/api/options/beans-options/processActions.php
tests/phpunit/integration/api/options/beans-options/register.php
tests/phpunit/integration/api/options/fixtures/test-options.php
tests/phpunit/integration/api/options/includes/class-options-test-case.php
tests/phpunit/unit/api/options/beans-options/register.php
tests/phpunit/unit/api/options/beans-options/renderPage.php
tests/phpunit/unit/api/options/fixtures/test-options.php
tests/phpunit/unit/api/options/includes/class-options-test-case.php

Updated array syntax of test for options API.

---

tests/phpunit/integration/api/wp-customize/beansRegisterWPCustomizeOptions.php
tests/phpunit/integration/api/wp-customize/fixtures/test-fields.php
tests/phpunit/integration/api/wp-customize/includes/class-wp-customize-test-case.php
tests/phpunit/unit/api/wp-customize/beans-wp-customize/add.php
tests/phpunit/unit/api/wp-customize/beans-wp-customize/add_control.php
tests/phpunit/unit/api/wp-customize/beans-wp-customize/add_group_setting.php
tests/phpunit/unit/api/wp-customize/beans-wp-customize/add_section.php
tests/phpunit/unit/api/wp-customize/beans-wp-customize/add_setting.php
tests/phpunit/unit/api/wp-customize/beansRegisterWPCustomizeOptions.php
tests/phpunit/unit/api/wp-customize/fixtures/test-fields.php
tests/phpunit/unit/api/wp-customize/includes/class-wp-customize-test-case.php

Updated array syntax of test for wp-customize API.

---

tests/phpunit/integration/api/layout/beansGetLayout.php
tests/phpunit/integration/api/layout/beansGetLayoutClass.php
tests/phpunit/unit/api/layout/beansGetDefaultLayout.php
tests/phpunit/unit/api/layout/beansGetLayout.php
tests/phpunit/unit/api/layout/beansHasSecondarySidebar.php

Updated array syntax of test for layout API.

---

tests/phpunit/integration/api/image/beans-image-editor/createEditedImage.php
tests/phpunit/integration/api/image/beans-image-editor/run.php
tests/phpunit/integration/api/image/beansEditImage.php
tests/phpunit/integration/api/image/includes/class-base-test-case.php
tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php
tests/phpunit/unit/api/image/beans-image-editor/run.php
tests/phpunit/unit/api/image/includes/class-base-test-case.php
tests/phpunit/unit/api/image/includes/class-image-test-case.php
tests/phpunit/unit/api/image/includes/class-options-test-case.php

Updated array syntax of test for image API.

---

tests/phpunit/unit/api/utilities/beansGet.php
tests/phpunit/unit/api/utilities/beansMultiArrayKeyExists.php
tests/phpunit/unit/api/utilities/beansPathToUrl.php
tests/phpunit/unit/api/utilities/beansRenderFunction.php
tests/phpunit/unit/api/utilities/beansRenderFunctionArray.php
tests/phpunit/unit/api/utilities/beansUrlToPath.php

Updated array syntax of test for utilities API.

---

tests/phpunit/integration/api/uikit/includes/class-uikit-test-case.php
tests/phpunit/unit/api/uikit/includes/class-uikit-test-case.php

Updated array syntax of test for uikit API.

---

tests/phpunit/integration/api/term-meta/beans-term-meta/construct.php
tests/phpunit/integration/api/term-meta/beansRegisterTermMeta.php
tests/phpunit/integration/api/term-meta/fixtures/test-fields.php
tests/phpunit/unit/api/term-meta/beansGetTermMeta.php
tests/phpunit/unit/api/term-meta/beansIsAdminTerm.php
tests/phpunit/unit/api/term-meta/beansRegisterTermMeta.php
tests/phpunit/unit/api/term-meta/fixtures/test-fields.php

Updated array syntax of test for term-meta API.

---

tests/phpunit/integration/api/template/beansLoadFragmentFile.php
tests/phpunit/unit/api/template/beansLoadFragmentFile.php
tests/phpunit/unit/api/template/includes/class-template-test-case.php

Updated array syntax of test for template API.

---

tests/phpunit/integration/api/post-meta/beans-post-meta/construct.php
tests/phpunit/integration/api/post-meta/beans-post-meta/okToSave.php
tests/phpunit/integration/api/post-meta/beans-post-meta/registerMetabox.php
tests/phpunit/integration/api/post-meta/beans-post-meta/renderMetaboxContent.php
tests/phpunit/integration/api/post-meta/beans-post-meta/renderNonce.php
tests/phpunit/integration/api/post-meta/beans-post-meta/save.php
tests/phpunit/integration/api/post-meta/beans-post-meta/saveAttachment.php
tests/phpunit/integration/api/post-meta/beansGetPostMeta.php
tests/phpunit/integration/api/post-meta/beansIsPostMetaConditions.php
tests/phpunit/integration/api/post-meta/beansPostMetaPageTemplateReload.php
tests/phpunit/integration/api/post-meta/beansRegisterPostMeta.php
tests/phpunit/integration/api/post-meta/fixtures/test-fields.php
tests/phpunit/unit/api/post-meta/beans-post-meta/okToSave.php
tests/phpunit/unit/api/post-meta/beans-post-meta/registerMetabox.php
tests/phpunit/unit/api/post-meta/beans-post-meta/renderMetaboxContent.php
tests/phpunit/unit/api/post-meta/beans-post-meta/renderNonce.php
tests/phpunit/unit/api/post-meta/beans-post-meta/save.php
tests/phpunit/unit/api/post-meta/beans-post-meta/saveAttachment.php
tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
tests/phpunit/unit/api/post-meta/beansIsPostMetaConditions.php
tests/phpunit/unit/api/post-meta/beansPostMetaPageTemplateReload.php
tests/phpunit/unit/api/post-meta/beansRegisterPostMeta.php
tests/phpunit/unit/api/post-meta/includes/class-beans-post-meta-test-case.php

Updated array syntax of test for post-meta API.

---

lib/admin/updater.php

Changed beans_updater to call the getbeans.io API using https

---

README.md
lib/templates/fragments/footer.php
tests/phpunit/integration/bootstrap.php
tests/phpunit/unit/bootstrap.php

Made sure that Beans URL is https://www.getbeans.io
Closes #288

Updated URLs in code to agreed writing style.

---

lib/assets/less/style.less

Before this PR:
After this PR:
closes #297

Adjusted styling for comment fieldset and cookie consent.

---

CHANGELOG.md
lib/init.php
lib/languages/tm-beans.pot
style.css

Updated the version number for the release candidate.

Updated to v.1.5.0-rc.

---

CHANGELOG.md
lib/init.php
lib/languages/tm-beans.pot
style.css

Changed version from 1.5.0-rc to 1.5.0.

---

lib/api/compiler/class-beans-compiler.php
tests/phpunit/unit/api/compiler/beans-compiler/runCompiler.php

This commit fixes #307 by recompiling when in development mode.

Fixed bug #307 to recompile when in development mode.

---

CHANGELOG.md
lib/api/compiler/class-beans-compiler.php
lib/init.php
style.css

Preparing the files for 1.5.1 release.

Added changes to changelog. Upticked to v1.5.1.
