Getbeans/Beans

- .dev-lib
- lib/api/actions/functions.php
- tests/phpunit/unit/api/actions/beansRenderAction.php
- tests/phpunit/unit/api/actions/beansUniqueActionId.php
- tests/phpunit/unit/api/actions/stubs/class-action-stub.php
1. Made `_beans_render_action` WPCS compliant
2. Made `_beans_unique_action_id` WPCS compliant
3. Tests for both
4. Fixed #78
> Made `_beans_render_action` and `_beans_unique_action_id` compliant

- lib/api/actions/functions.php
- tests/phpunit/unit/api/actions/beansGetAction.php
- tests/phpunit/unit/api/actions/beansGetCurrentAction.php
- tests/phpunit/unit/api/actions/beansIsActionValid.php
- tests/phpunit/unit/api/actions/beansMergeAction.php
- tests/phpunit/unit/api/actions/beansSetAction.php
- tests/phpunit/unit/api/actions/beansUnsetAction.php
- tests/phpunit/unit/class-test-case.php
This PR is for the private functions which interact directly with the global `$_beans_registered_actions`. 
1. Made WPCS compliant
2. Added unit tests.
3. Added DocBlock.
> Made private functions compliant

- lib/api/actions/functions.php
- tests/phpunit/integration/api/actions/beansModifyAction.php
- tests/phpunit/integration/api/actions/beansModifyActionArguments.php
- tests/phpunit/integration/api/actions/beansModifyActionCallback.php
- tests/phpunit/integration/api/actions/beansModifyActionHook.php
- tests/phpunit/integration/api/actions/beansModifyActionPriority.php
- tests/phpunit/integration/api/actions/includes/class-actions-test-case.php
- tests/phpunit/unit/api/actions/beansBuildActionArray.php
- tests/phpunit/unit/api/actions/beansBuildActionForValidArgs.php
- tests/phpunit/unit/api/actions/beansModifyAction.php
- tests/phpunit/unit/api/actions/beansModifyActionArguments.php
- tests/phpunit/unit/api/actions/beansModifyActionCallback.php
- tests/phpunit/unit/api/actions/beansModifyActionHook.php
- tests/phpunit/unit/api/actions/beansModifyActionPriority.php
- tests/phpunit/unit/api/actions/includes/class-actions-test-case.php
2. Added unit tests.
3. Added integration tests.
4. Improved comments and documentation.
5. Bail out if no action to modify.
6. Return add_action instead of true.
> Made beans_modify_action compliant

- .gitignore
`composer.lock` is ignored twice.
> Remove duplicate .gitignore entry

- lib/api/actions/functions.php
- tests/phpunit/integration/api/actions/beansReplaceAction.php
- tests/phpunit/integration/api/actions/beansReplaceActionArguments.php
- tests/phpunit/integration/api/actions/beansReplaceActionCallback.php
- tests/phpunit/integration/api/actions/beansReplaceActionHook.php
- tests/phpunit/integration/api/actions/beansReplaceActionPriority.php
- tests/phpunit/integration/api/actions/fixtures/test-actions.php
- tests/phpunit/integration/api/actions/includes/class-actions-test-case.php
- tests/phpunit/integration/api/actions/includes/class-replace-action-test-case.php
- tests/phpunit/unit/api/actions/beansReplaceAction.php
- tests/phpunit/unit/api/actions/beansReplaceActionArguments.php
- tests/phpunit/unit/api/actions/beansReplaceActionCallback.php
- tests/phpunit/unit/api/actions/beansReplaceActionHook.php
- tests/phpunit/unit/api/actions/beansReplaceActionPriority.php
- tests/phpunit/unit/api/actions/fixtures/test-actions.php
- tests/phpunit/unit/api/actions/includes/class-actions-test-case.php
- tests/phpunit/unit/api/actions/includes/class-replace-action-test-case.php
The changes below affect the following functions:
- `beans_replace_action()`
- `beans_replace_action_hook()`
- `beans_replace_action_callback()`
- `beans_replace_action_priority()`
- `beans_replace_action_arguments()`
2. Added integration and unit tests.
3. Used real Beans actions for test fixtures.
4. Fixed #101.
5. Improved documentation.
> Made "replace" actions wpcs compliant + tests

- lib/api/actions/functions.php
- tests/phpunit/integration/api/actions/beansRemoveAction.php
- tests/phpunit/integration/api/actions/beansReplaceAction.php
- tests/phpunit/integration/api/actions/beansReplaceActionArguments.php
- tests/phpunit/integration/api/actions/beansReplaceActionCallback.php
- tests/phpunit/integration/api/actions/beansReplaceActionHook.php
- tests/phpunit/integration/api/actions/beansReplaceActionPriority.php
- tests/phpunit/integration/api/actions/beansResetAction.php
- tests/phpunit/integration/api/actions/includes/class-actions-test-case.php
- tests/phpunit/integration/api/actions/includes/class-replace-action-test-case.php
- tests/phpunit/unit/api/actions/beansRemoveAction.php
- tests/phpunit/unit/api/actions/beansReplaceAction.php
- tests/phpunit/unit/api/actions/beansReplaceActionArguments.php
- tests/phpunit/unit/api/actions/beansReplaceActionCallback.php
- tests/phpunit/unit/api/actions/beansReplaceActionHook.php
- tests/phpunit/unit/api/actions/beansReplaceActionPriority.php
- tests/phpunit/unit/api/actions/beansResetAction.php
- tests/phpunit/unit/api/actions/includes/class-actions-test-case.php
- tests/phpunit/unit/api/actions/includes/class-replace-action-test-case.php
Functions: `beans_remove_action` and `beans_reset_action`.
2. Added integration tests.
3. Added unit tests.
4. Improved documentation.
5. Improved both functions.
> Made WPCS compliant. Added tests.

- tests/phpunit/unit/api/utilities/beansGet.php
The original unit tests for `beans_get()` was light and incomplete.  This PR breaks up the tests for array and object haystacks as well as covers additional scenarios, such as `$_GET` and indexed arrays.
> Improved beans_get tests.

- composer.json
- lib/api/actions/class-beans-anonymous-action.php
- lib/api/compiler/class-page-compiler.php
- lib/api/init.php
- lib/api/utilities/functions.php
- lib/api/utilities/polyfills.php
- lib/api/widget/functions.php
- lib/api/wp-customize/class.php
- tests/phpunit/integration/api/actions/includes/class-actions-test-case.php
- tests/phpunit/integration/api/filters/includes/class-filters-test-case.php
- tests/phpunit/integration/bootstrap.php
- tests/phpunit/unit/api/actions/beansRenderAction.php
- tests/phpunit/unit/api/actions/stubs/class-action-stub.php
- tests/phpunit/unit/api/utilities/beansRenderFunction.php
- tests/phpunit/unit/api/utilities/beansRenderFunctionArray.php
- tests/phpunit/unit/bootstrap.php
- tests/phpunit/unit/class-test-case.php
Credit to @GaryJones - This PR upgrades our PHP sniffers to use the latest version, thereby allowing us to remove the deprecated `// @coding...` ignore declarations.
It standardizes our ignore syntax to be:
```
// phpcs:ignore Rule.To.Be.Ignored, Another.Rule.To.Be.Ignored -- Reason why we are ignoring this rule(s)
```
Closes #144
> Upgrade PHPCS/WPCS

- lib/api/fields/functions.php
- lib/api/fields/types/text.php
- lib/api/fields/types/textarea.php
- lib/api/fields/types/views/activation.php
- lib/api/fields/types/views/checkbox.php
- lib/api/fields/types/views/field-description.php
- lib/api/fields/types/views/image.php
- lib/api/fields/types/views/radio.php
- lib/api/fields/types/views/select.php
- lib/api/fields/types/views/slider.php
- tests/phpunit/integration/api/html/beansAddAttribute.php
- tests/phpunit/integration/api/html/beansRemoveAttribute.php
- tests/phpunit/integration/api/html/beansReplaceAttribute.php
- tests/phpunit/unit/api/html/beansAddAttribute.php
- tests/phpunit/unit/api/html/beansRemoveAttribute.php
- tests/phpunit/unit/api/html/beansReplaceAttribute.php
This PR replaces the deprecated `// @coding...` phpcs and wpcs rule ignores.
> Replaced deprecated phpcs rule ignores for Fields API.

- tests/phpunit/integration/api/html/beansAddAttribute.php
- tests/phpunit/integration/api/html/beansRemoveAttribute.php
- tests/phpunit/integration/api/html/beansReplaceAttribute.php
- tests/phpunit/unit/api/html/beansAddAttribute.php
- tests/phpunit/unit/api/html/beansRemoveAttribute.php
- tests/phpunit/unit/api/html/beansReplaceAttribute.php
This PR replaces the deprecated `// @coding...` phpcs and wpcs rule ignores.
> Replaced deprecated phpcs rule ignores for api/html/attributes

- lib/api/layout/functions.php
- tests/phpunit/integration/api/layout/beansGetDefaultLayout.php
- tests/phpunit/integration/api/layout/beansGetLayout.php
- tests/phpunit/integration/api/layout/beansGetLayoutClass.php
- tests/phpunit/unit/api/layout/beansGetDefaultLayout.php
- tests/phpunit/unit/api/layout/beansGetLayout.php
- tests/phpunit/unit/api/layout/beansGetLayoutClass.php
2. Added unit and integration tests.
3. Fixed #117.
4. Refactored to remove redundancies.
5. Improved documentation.
The API runs slightly faster:
- `beans_get_layout()` improved by 0.011567ms.
- `beans_get_layout_class()` improved by 0.010159ms.
```
-------------------------
MICRO PROFILER REPORT:
-------------------------
PHP version:        5.6.20
Sample Size:        10,000 (per function)
Time Increments:    milliseconds, where 1 ms equals 0.001 second.
--------------------------------   -------------   -------------   -------------
| Name                             | Result        |  Avg Time     | v1.4.0
|                                  | (ms)          |  (ms)         | (ms)
| -------------------------------- | ------------- | ------------- | ------------- …
```
> Made Layout API WPCS compliant & tested.

- tests/phpunit/unit/api/layout/beansGetDefaultLayout.php
- tests/phpunit/unit/api/layout/beansGetLayout.php
- tests/phpunit/unit/api/layout/beansGetLayoutClass.php
- tests/phpunit/unit/class-test-case.php
Added ability to load original functions into memory before the monkey patch redefines the function.
The tests were failing due to the original functions not being loaded into memory _before_
using Brain Monkey and Patchwork.  The sequence to redefine an original function is:
1. Load the original function into memory.
2. Monkey patch it with Brain Monkey expect() or when(), which redefines that function for our unit tests.
3. Then restore the function back to its original declaration, which is handled at tear down by Brain Monkey.
> Added load original functions before monkey patch.

- tests/phpunit/unit/api/actions/includes/class-actions-test-case.php
- tests/phpunit/unit/api/fields/includes/class-fields-test-case.php
- tests/phpunit/unit/api/filters/includes/class-filters-test-case.php
- tests/phpunit/unit/api/html/includes/class-html-test-case.php
- tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
- tests/phpunit/unit/api/template/includes/class-template-test-case.php
- tests/phpunit/unit/api/term-meta/beansGetTermMeta.php
Moved dependency files out of the pre setup and into the setup method, i.e. to ensure they are loaded after Patchwork initializes (through Brain Monkey).
> Load original functions after initializing Patchwork.

- tests/phpunit/unit/api/term-meta/beansGetTermMeta.php
As of PR #154, we should now mock `beans_get()` for this test.
> Revise unit test beans_get_term_meta()

- tests/phpunit/integration/api/fields/beansField.php
- tests/phpunit/integration/api/fields/beansGetFields.php
- tests/phpunit/integration/api/fields/includes/class-fields-test-case.php
- tests/phpunit/integration/class-test-case.php
To ensure that everything works in the Fields API, this PR adds 2 full integration tests that register the fields and then render them.
This PR also improves the test suite by:
1. Adding Actions API Container resets in the Integration Test Case.
2. Adding Fields API Container resets in the Integration Test Case.
3. Moving the reflective methods to the Integration Test Case.
4. Adding label and description set up and tear down.
The resets ensure we start at a known state for each test.
> Added full integration tests for Fields API

- lib/api/html/functions.php
To eliminate confusion, we are standardized the extra `$var` arguments as a note instead of an extra `@param`.  
This change eliminates the need to ignore the PHPCS rule.  
It also makes the documentation more readable and understandable. Why? When listed as one `@param`, it gives the impression that you can only pass one additional argument.  But that's not accurate, as you pass one or more.
> Standardized extra vars as a note instead of @param.

- lib/api/html/functions.php
- tests/phpunit/integration/api/html/beansAddAttributes.php
- tests/phpunit/integration/api/html/includes/class-html-test-case.php
- tests/phpunit/unit/api/html/beansAddAttributes.php
- tests/phpunit/unit/api/html/includes/class-html-test-case.php
1. Added unit tests.
2. Added integration tests.
3. Removed the `isset()` and replaced with `empty()` to further optimize the function.
The overall function improved by 0.002303 ms.
```
-------------------------
MICRO PROFILER REPORT:
-------------------------
PHP version:        5.6.20
Sample Size:        100,000 (per function)
Time Increments:    milliseconds, where 1 ms equals 0.001 second.
--------------------------------   -------------   -------------   -------------
| Name                             | Result        |  Avg Time     | v1.4.0
|                                  | (ms)          |  (ms)         | (ms)
| -------------------------------- | ------------- | ------------- | -------------
| beans_add_attributes             |    -0.002303  |      0.017420 |      0.019723 …
```
> Tested & Optimized beans_add_attributes.

- lib/api/post-meta/functions.php
- tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
The proper function name is `get_the_ID()`.
> Replaced get_the_id with get_the_ID.

- lib/api/html/functions.php
- tests/phpunit/integration/api/html/beansWrapInnerMarkup.php
- tests/phpunit/unit/api/html/beansWrapInnerMarkup.php
1. Added unit tests.
2. Added integration tests.
3. Bailing out if the `$tag` is empty, as there is no work to be done.
4. Improved function's documentation.
> Tested beans_wrap_inner_markup.

- tests/phpunit/integration/api/html/beansWrapInnerMarkup.php
- tests/phpunit/integration/api/html/beansWrapMarkup.php
I missed these when reviewing on GitHub.
> Fixed typo in HTML API integration tests

- tests/phpunit/unit/api/fields/includes/class-fields-test-case.php
- tests/phpunit/unit/api/html/beansAddAttributes.php
- tests/phpunit/unit/api/html/includes/class-html-test-case.php
- tests/phpunit/unit/api/image/includes/class-image-test-case.php
- tests/phpunit/unit/api/options/includes/class-options-test-case.php
- tests/phpunit/unit/class-test-case.php
Refactored the stubs for the common WordPress escaping and internationalization functions by moving them into the Test Case with a new `setup_common_wp_stubs` method.
This change allows tests suites to invoke `$this-setup_common_wp_stubs()` instead of redefining each of the WP functions again.
Reason: DRY.
> Refactored common WP stubs.

- lib/api/post-meta/functions.php
- tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
Optimized `beans_get_post_meta` by eliminating the double assignment when no post ID is passed to the function but it is resolved by `get_the_ID()`.  With this PR, 
1. `get_the_ID()` assigns the value directly to `$post_id`
2. and `beans_get()` only runs IF `get_the_ID()` does not return the ID.
This change speeds up the function by 0.001439ms as noted in the profiler report and saves a single bit of memory:
```
-------------------------
MICRO PROFILER REPORT:
-------------------------
PHP version:        5.6.20
Sample Size:        100,000 (per function)
Time Increments:    milliseconds, where 1 ms equals 0.001 second.
--------------------------------   -------------   -------------   -------------
| Name                             | Result        |  Avg Time     | v1.4.0
| …
```
> Optimized beans_get_post_meta

- lib/templates/fragments/post.php
Type casting the maximum number of pages (i.e. `$wp_query->max_num_pages)` to integer, as WordPress has the property as a float.
Closes #180.
> Fixed pagination.

- lib/api/html/functions.php
- tests/phpunit/integration/api/html/beansOpenMarkup.php
- tests/phpunit/integration/api/html/beansOpenMarkupE.php
- tests/phpunit/unit/api/html/beansOpenMarkup.php
- tests/phpunit/unit/api/html/beansOpenMarkupE.php
1. Added unit and integration tests.
2. Refactored `beans_open_markup`, re-arranging tasks to occur only where/when needed.
3. Improved documentation.
> Tested beans_open_markup and beans_open_markup_e

- lib/api/actions/functions.php
Optimized `_beans_when_has_action_do_render`, which made `_beans_render_action()`, `beans_open_markup()`, `beans_close_markup()` and other functions run faster:
- `_beans_render_action()` runs 0.002281ms faster
- `beans_open_markup()` runs 0.002855ms faster
Invoking `beans_render_function` has a performance hit as we have to:
1. We assemble arguments using `array_merge()` to invoke `beans_render_function`.
2. get all the arguments via `func_get_args()`.
3. Prep the args using `array_slice()`.
4. Then invoke `do_action()` using `call_user_func_array()`.
This PR removes all of that overhead.  Though it's a little less DRY, as the output buffering is repeated in this function, it is more performant as it runs 0.004033ms faster.
This change impacts all functions that use …
> Optimized _beans_when_has_action_do_render()

- lib/api/html/functions.php
- tests/phpunit/integration/api/html/beansCloseMarkup.php
- tests/phpunit/integration/api/html/beansOpenMarkup.php
Escaped HTML built by the API.  Tested using this [script](https://gist.github.com/hellofromtonya/99cb29fcacbc14c5eac7aa1b902bd0c5), which you can put into your Beans child theme's functions.php file.
Updated Rule comments to note compliance.
Added tests to both the `beans_open_markup` and `beans_close_markup` test suites to ensure code built by Beans is safe.
This PR is part of the ongoing #143 Safety Audit.
> Escape HTML API

- lib/api/actions/class-beans-anonymous-action.php
- lib/api/actions/functions.php
- tests/phpunit/integration/api/html/beansWrapInnerMarkup.php
- tests/phpunit/integration/api/html/beansWrapMarkup.php
- tests/phpunit/unit/api/actions/beans-anonymous-action/__construct.php
- tests/phpunit/unit/api/actions/beans-anonymous-action/callback.php
- tests/phpunit/unit/api/html/fixtures/class-anonymous-action-stub.php
This PR adds unit tests for the `_Beans_Anonymous_Action`.  It also renames the class to a singular noun, as the class is the blueprint for a single anonymous action.
I want to note here that I did review the use of registering the hook in the constructor.  This practice is frowned upon; however, in this case, the point of instantiating the object is register the anonymous callback to the given hook.  Therefore, it is a valid use case.
> Added unit tests for _Beans_Anonymous_Action

- lib/api/post-meta/functions-admin.php
Check for a Boolean `true` at the beginning instead of waiting til the end. Otherwise, other conditions might not allow us to evaluate the more general case.
> Bug fix on post meta screen conditions not being correctly evaluated

- tests/phpunit/integration/api/compiler/beans-compiler/addContentMediaQuery.php
- tests/phpunit/integration/api/compiler/beans-compiler/cacheFile.php
- tests/phpunit/integration/api/compiler/beans-compiler/combineFragments.php
- tests/phpunit/integration/api/compiler/beans-compiler/fileystem.php
- tests/phpunit/integration/api/compiler/beans-compiler/formatContent.php
- tests/phpunit/integration/api/compiler/beans-compiler/getInternalContent.php
- tests/phpunit/integration/api/compiler/beans-compiler/getRemoteContent.php
- tests/phpunit/integration/api/compiler/beans-compiler/replaceCssUrl.php
- tests/phpunit/integration/api/compiler/beans-compiler/runCompiler.php
- tests/phpunit/integration/api/compiler/beans-compiler/setFilename.php
- tests/phpunit/unit/api/compiler/beans-compiler/addContentMediaQuery.php
- tests/phpunit/unit/api/compiler/beans-compiler/cacheFile.php
- tests/phpunit/unit/api/compiler/beans-compiler/cacheFileExist.php
- tests/phpunit/unit/api/compiler/beans-compiler/combineFragments.php
- tests/phpunit/unit/api/compiler/beans-compiler/fileystem.php
- tests/phpunit/unit/api/compiler/beans-compiler/formatContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/get.php
- tests/phpunit/unit/api/compiler/beans-compiler/getExtension.php
- tests/phpunit/unit/api/compiler/beans-compiler/getFunctionContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/getInternalContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/getRemoteContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/replaceCssUrl.php
- tests/phpunit/unit/api/compiler/beans-compiler/runCompiler.php
- tests/phpunit/unit/api/compiler/beans-compiler/setFilename.php
- tests/phpunit/unit/api/compiler/beans-compiler/setFragments.php
I failed to name this test classes properly in the previous commits.  The class naming standard is:
```
Tests_NameOfTheClass_NameOfTheMethod
```
This PR renames all of the `_Beans_Compiler` test classes to comply.
> Renamed test classes to comply with WPCS.

- tests/phpunit/integration/api/compiler/beans-compiler/addContentMediaQuery.php
- tests/phpunit/integration/api/compiler/beans-compiler/cacheFile.php
- tests/phpunit/integration/api/compiler/beans-compiler/combineFragments.php
- tests/phpunit/integration/api/compiler/beans-compiler/fileystem.php
- tests/phpunit/integration/api/compiler/beans-compiler/formatContent.php
- tests/phpunit/integration/api/compiler/beans-compiler/getInternalContent.php
- tests/phpunit/integration/api/compiler/beans-compiler/getRemoteContent.php
- tests/phpunit/integration/api/compiler/beans-compiler/replaceCssUrl.php
- tests/phpunit/integration/api/compiler/beans-compiler/runCompiler.php
- tests/phpunit/integration/api/compiler/beans-compiler/setFilename.php
- tests/phpunit/integration/api/compiler/includes/class-compiler-test-case.php
- tests/phpunit/unit/api/compiler/beans-compiler/addContentMediaQuery.php
- tests/phpunit/unit/api/compiler/beans-compiler/cacheFile.php
- tests/phpunit/unit/api/compiler/beans-compiler/cacheFileExist.php
- tests/phpunit/unit/api/compiler/beans-compiler/combineFragments.php
- tests/phpunit/unit/api/compiler/beans-compiler/fileystem.php
- tests/phpunit/unit/api/compiler/beans-compiler/formatContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/get.php
- tests/phpunit/unit/api/compiler/beans-compiler/getExtension.php
- tests/phpunit/unit/api/compiler/beans-compiler/getFunctionContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/getInternalContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/getRemoteContent.php
- tests/phpunit/unit/api/compiler/beans-compiler/replaceCssUrl.php
- tests/phpunit/unit/api/compiler/beans-compiler/runCompiler.php
- tests/phpunit/unit/api/compiler/beans-compiler/setFilename.php
- tests/phpunit/unit/api/compiler/beans-compiler/setFragments.php
- tests/phpunit/unit/api/compiler/includes/class-compiler-test-case.php
Fixed loading of the unit tests files, which were still loading in the pre set up process, i.e. `setUpBeforeClass`.  Moved them to our new `load_original_functions()` method to ensure they load _after_ Patchwork is initialized.
Other minor changes which included standardizing the test documentation to include the class name, i.e.:
```
Test Class_Name::method_name() should.....
```
> Improvements to Beans Compiler test suite.

- lib/api/html/functions.php
Whoops, I caused a bug in the HTML API when in PHP 5.2.  `func_get_args()` needs to be assigned to an variable before passing to function.
Fixes #221.
> Assigned `func_get_args()` to variable before passing to function.

- tests/phpunit/integration/api/options/beans-options/renderPage.php
Newer versions of WordPress' metabox code has fixed the single quotation marks around the class attribute 'hndle'.  This commit formats the rendered HTML by converting the single quotes to doubles, thereby, allowing our tests to pass on multiple versions of WordPress.
> Fixed single quotes around class='hndle'.

- tests/phpunit/integration/api/template/beansLoadDefaultTemplate.php
- tests/phpunit/unit/api/template/beansLoadDefaultTemplate.php
The Template API integration tests for the `beans_load_default_template()` causes the trunk tests to fail. Why? We were letting `wp_head()` run.  There's no need in this suite. 
1. This PR adds mocks for non-essential functionality.
2. It makes the tests intent more clear, as it confused me when I went back to fix it (and I wrote it originally LOL).
> Fixes the Template API to mock wp_head() & Clarifies intent.

- lib/api/fields/types/views/checkbox.php
- lib/api/fields/types/views/image.php
- lib/api/fields/types/views/radio.php
- lib/api/fields/types/views/select.php
- lib/api/fields/types/views/slider.php
- lib/api/options/views/page.php
- lib/api/options/views/reset-notice-error.php
- lib/api/options/views/reset-notice-success.php
- lib/api/options/views/save-notice-error.php
- lib/api/options/views/save-notice-success.php
- lib/api/term-meta/views/term-meta-field.php
View files are indented for HTML structure.  When inserting PHP into the files, we do not want the PHP to drive indentation for the HTML.  Therefore, we disable the whitespacing rules.
The `phpcs:enable` was removed from the end of the file, as PHPCS rules reset for each file.  Therefore, this extra line of code is not needed.
> Disabled whitespacing phpcs rules inside of view files.

- lib/api/uikit/class-beans-uikit.php
- lib/api/uikit/functions.php
- lib/api/utilities/functions.php
- tests/phpunit/integration/api/uikit/beansUikitAutoloadDependencies.php
- tests/phpunit/integration/api/uikit/beansUikitEnqueueComponents.php
- tests/phpunit/integration/api/uikit/includes/class-uikit-test-case.php
- tests/phpunit/unit/api/uikit/beansUikitEnqueueComponents.php
- tests/phpunit/unit/api/uikit/beansUikitGetAllComponents.php
- tests/phpunit/unit/api/uikit/beansUikitGetAllDependencies.php
- tests/phpunit/unit/api/utilities/beansArrayUnique.php
- tests/phpunit/unit/api/utilities/beansJoinArraysClean.php
This PR does several things:
1. Creates 2 new utility array functions for reuse: `beans_array_unique` and `beans_join_arrays_clean`. In doing so, we've eliminated redundant code.
2. Removes duplicates and empties from the enqueued components. Why? 
- Run faster when iterating through the components, as there are less to loop through.
- Re-indexing & less elements uses less memory.
3. Added 3 new functions to the UIkit API:
- `beans_uikit_get_all_components()`
- `beans_uikit_get_all_dependencies()`
- `_beans_uikit_autoload_dependencies()`
These changes give plugin and theme developers access to all of the private functionality of `_Beans_Uikit`.  It also eliminates redundant code.  And it's more readable and understandable.
> Tests & Improvements for UIkit API enqueue components

- lib/api/compiler/class-beans-compiler.php
- tests/phpunit/integration/api/uikit/beans-uikit/compile.php
I added a bug back when I did the Compiler.  It stripped out all of the whitespace from the CSS.  So style declarations like:
```
margin: 0 0 10px 0;
```
were converted into:
```
margin:0010px0;
```
Not good.  Doh.
This PR fixes my bug by only removing extra whitespaces.  It also strips the whitespace at the start of each new line.  And it fixes the associated CSS tests.
Closes #255.
> Fixed whitespace bug in compiler

- lib/admin/wp-customize.php
- lib/api/wp-customize/class-beans-wp-customize.php
This reverts the default Customizer transport method back to `refresh` and adds `'transport' => 'postMessage'` to the preview tools config.
Fixes #293
> Fixed regression in Customizer preventing the logo to refresh.

- lib/templates/fragments/comments.php
- lib/templates/fragments/menu.php
- lib/templates/fragments/post-shortcodes.php
- lib/templates/fragments/post.php
- lib/templates/fragments/widget.php
I had left 6 or so "pending security audit" messages in the codebase.  Thank you @christophherr for reminding me.  Each of those has been audited, corrected, and updated.
In reviewing, I noticed an inconsistency in our translation escaping.  Fixed to be:
1. Use `esc_html__()` when not an attribute and is being rendered out directly or as part of `beans_open_markup`, `beans_output`, etc.
2. Do not escape directly when it's an attribute.  Why?  Attributes are automatically escaped in Beans.
> Cleaned up security audit messages & escaping.
